# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Ankit-PC/anaconda3/Library/include
    lib directory: C:/Users/Ankit-PC/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  ho

#### 3. Create a null vector of size 10

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\ankit-pc\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, t

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
arr = np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

#### 8.  Reverse a vector (first element becomes last)

In [8]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr = np.random.randint(0,9,(3,3))
arr

array([[8, 6, 3],
       [0, 6, 8],
       [6, 1, 7]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [10]:
arr = np.array([1,2,0,0,4,0])
#ans = np.where(arr==0)
ans =  np.nonzero(arr)
ans

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [12]:
np.random.random((3,3,3))

array([[[0.37025438, 0.12472265, 0.65179265],
        [0.04472215, 0.52730526, 0.96197954],
        [0.33447292, 0.20884508, 0.13613361]],

       [[0.2957024 , 0.89409789, 0.28969259],
        [0.13696523, 0.00299616, 0.91999033],
        [0.08045972, 0.09901426, 0.09275246]],

       [[0.74598615, 0.16024224, 0.08069424],
        [0.87927251, 0.66218776, 0.07398355],
        [0.48219205, 0.08199716, 0.55727042]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
arr = np.random.random((10,10))
a = np.max(arr)
b = np.min(arr)
print(a,b,sep="\n")

0.988140746727668
0.008237293970910109


#### 14. Create a random vector of size 30 and find the mean value

In [14]:
arr = np.random.random((30))
ans = np.mean(arr)
ans

0.4325115800059025

#### 15. Create a 2d array with 1 on the border and 0 inside

In [15]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
ans = np.diag([1,2,3,4],-1)
ans

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)